### ISSUE TITLE
example.py bug

### ISSUE THREAD

**Issue by Leona-Karelin** [LuLuLuyi/LongHeads#1]
Hi, Sir
I install the `requirement.txt` you give, but I met a bug when running `example.py`.
My model is Llama2-13B, and it can be loaded successfully.

```python
<s> What is Data Traceback (most recent call last):
  File "/home/***/LongHeads/example.py", line 41, in <module>
    generated_tokens = model.generate(
  File "/home/***/anaconda3/envs/longheads/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/***/anaconda3/envs/longheads/lib/python3.9/site-packages/transformers/generation/utils.py", line 1606, in generate
    return self.greedy_search(
  File "/home/***/anaconda3/envs/longheads/lib/python3.9/site-packages/transformers/generation/utils.py", line 2493, in greedy_search
    raise ValueError("If eos_token_id is defined, make sure that pad_token_id is defined.")
ValueError: If eos_token_id is defined, make sure that pad_token_id is defined.
```

And When I add the following code to GenerationConfig(), the problem has been solved.

```python
generation_config=GenerationConfig(
            # use_cache=True is required, the rest can be changed up.
            use_cache=True,
            min_new_tokens=100,
            max_new_tokens=300,
            pad_token_id=tokenizer.pad_token_id if tokenizer.pad_token_id is not None else tokenizer.eos_token_id
        ),
```

**Comment by LuLuLuyi** [comment]
Thank you, I will add this to `example.py`
